fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "concat": "git://github.com/ripienaar/puppet-concat.git"
    "keystone": "git://github.com/puppetlabs/puppetlabs-keystone.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "rabbitmq": "git://github.com/puppetlabs/puppetlabs-rabbitmq.git"
  symlinks:
    "glance": "#{source_dir}"
