require 'erb'
require 'uri'
require 'net/http'
require 'net/https'

STDOUT.sync = true

# This rake file is designed to be rull on the cloudbox or a  ubuntu 12.0.4 VM
RUNDIR = File.dirname(__FILE__)
# Download PE
PEVERSION = '2.6.1'
PE_RELEASE_URL = "https://s3.amazonaws.com/pe-builds/released/#{PEVERSION}"
PE_INSTALL_SUFFIX = '-el-6-i386'
PE_URL = "#{PE_RELEASE_URL}/puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}.tar.gz"

BASE_ISO_FILE  = "CentOS-6.3-i386-bin-DVD1.iso"
#BASE_ISO_URL   = "http://faro/ISO/CentOS/CentOS-6.0-x86_64-bin-DVD/#{BASE_ISO_FILE}"
BASE_ISO_URL   = "http://mirror.chpc.utah.edu/pub/centos/6.3/isos/x86_64/#{BASE_ISO_FILE}"
NEW_ISO_NAME   = "centos-6.0-pe-#{PEVERSION}"
NEW_ISO_FILE   = "#{NEW_ISO_NAME}.iso"

SAVEDIR = ENV['HOME'] + "/Desktop/#{NEW_ISO_NAME}-isobuild"

task :default do
      sh %{rake -T}
end

desc "Build and populate iso directory"
task :init do
  # Make our work dirs
  [SAVEDIR].each do |dir|
    unless File.directory?(dir)
      cputs "Making directory #{dir}"
      FileUtils.mkdir(dir)
    end
  end
  
  # Download the iso
  unless File.exist?("#{SAVEDIR}/#{BASE_ISO_FILE}")
    # Prompt for the base ISO URL
    cprint "Please specify iso url [#{BASE_ISO_URL}]: "
    iso_uri = STDIN.gets.chomp.rstrip
    iso_uri = BASE_ISO_URL if iso_uri.empty?
    cputs "Downloading ISO..."
    download iso_uri, "#{SAVEDIR}/#{BASE_ISO_FILE}"
  end

  # Mount the iso
  unless File.exist?("#{SAVEDIR}/iso_mount")
    cputs "Mounting ISO..."
    # Create the iso mount point
    FileUtils.mkdir("#{SAVEDIR}/iso_mount")
    %x{mount -o loop "#{SAVEDIR}/#{BASE_ISO_FILE}" "#{SAVEDIR}/iso_mount"}
  end

  # Copy the iso files
  unless File.exist?("#{SAVEDIR}/centos_files")
    cputs "Creating working directory"
    # Create editable copy
    FileUtils.mkdir("#{SAVEDIR}/centos_files")
  end
  cputs "Copying iso files to working directory..."
  %x{rsync -a "#{SAVEDIR}/iso_mount/." "#{SAVEDIR}/centos_files"}

  # Grab the copy of PE for the hypervisor
  unless File.exist?("#{RUNDIR}/kickstart/puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}.tar.gz")
    cputs "Downloading PE #{PEVERSION} for student VM..."
    download "#{PE_URL}", "#{RUNDIR}/kickstart/puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}.tar.gz"
  end

  ## Extract the installer
  unless File.exist?("#{RUNDIR}/kickstart/puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}")
    FileUtils.cd("#{RUNDIR}/kickstart/", :verbose => true)
    %x{ tar -xzf "puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}.tar.gz" }
    FileUtils.rm("puppet-enterprise-#{PEVERSION}#{PE_INSTALL_SUFFIX}.tar.gz")
  end

  # Add our customizations to the iso
  cputs "Configuring kickstarting..."
  FileUtils.cp_r("#{RUNDIR}/kickstart/.","#{SAVEDIR}/centos_files/kickstart/")

  cputs "Configuring automatic installation..."
  # Configure automatic installation
  FileUtils.cp_r("#{RUNDIR}/isolinux/.","#{SAVEDIR}/centos_files/isolinux/")

  # Fix any perm/owner issues
  FileUtils.chmod(555,"#{SAVEDIR}/centos_files/isolinux/isolinux.cfg")
  FileUtils.chown('root','root',"#{SAVEDIR}/centos_files/isolinux/isolinux.cfg")

  # Build the new iso
  if File.exists?("#{SAVEDIR}/#{NEW_ISO_FILE}")
    cputs "Removing previous iso..."
    FileUtils.rm("#{SAVEDIR}/#{NEW_ISO_FILE}")
  end

  # Check to make sure xorriso is installed
  xorriso = %x{which xorriso}.chomp
  unless File.executable?(xorriso)
    cputs "Installing xorriso..."
    %x{apt-get install xorriso -y}
  end

  # Build our new iso with MBR record
  cputs "Rebuilding iso from modfied directory..."
  FileUtils.cd("#{SAVEDIR}/centos_files", :verbose => true)
  %x{xorriso \
         -as mkisofs \
         -r \
         -V "#{NEW_ISO_NAME}" \
         -J \
         -l \
         -b isolinux/isolinux.bin \
         -c isolinux/boot.cat \
         -no-emul-boot \
         -boot-load-size 4 \
         -boot-info-table -o "#{SAVEDIR}/#{NEW_ISO_FILE}" . }

  STDOUT.sync = true
  STDOUT.flush
end

desc "Copy iso to thumb drive"
task :thumb do
  # Copy our iso to our thumb drive
  cputs "Copying iso to thumb drive..."
  %x{dd if="#{SAVEDIR}/#{NEW_ISO_FILE}" of="#{NEW_ISO_DEV}" bs=1M} 
end

desc "Remove the temp directories"
task :clean do
  FileUtils.rm_rf(SAVEDIR)
end

def download(url,path)
  u = URI.parse(url)
  net = Net::HTTP.new(u.host, u.port)
  case u.scheme
  when "http"
    net.use_ssl = false
  when "https"
    net.use_ssl = true
    net.verify_mode = OpenSSL::SSL::VERIFY_NONE
  else
    raise "Link #{url} is not HTTP(S)"
  end
  net.start do |http|
    #resp = http.get(u.path)
    #open(path, "wb") do |file|
    #  file.write(resp.body)
    #end
    file = open(path,"wb")
    begin
        http.request_get(u.path) do |resp|
            resp.read_body do |segment|
                file.write(segment)
            end
        end
    ensure
        file.close()
    end
  end
end

def cputs(string)
  puts "\033[1m#{string}\033[0m"
end

def cprint(string)
  print "\033[1m#{string}\033[0m"
end

# vim: set sw=2 sts=2 et tw=80 :
